= How to install a JBoss Tools component build

If you've already built a component, such as `jbosstools-base` or `jbosstools-server`, you may want to 
install it into a new clean eclipse to test it out properly. It is highly suggested to do this
once in a while, since some bugs may not be caught during development time in the Runtime Workbench, 
or at build time while running the unit test suites. 

The process to install and test your locally-built units is:

* Create an eclipse installation which has all required dependencies
* Run the eclipse with a new workspace
* Install the locally built units into eclipse. 

== Installing all dependencies into Eclipse

Each component in JBoss Tools has dependencies on other installable units. These units should all be either:

* Provided in the eclipse installation
* Provided by our target platform
* Other JBoss Tools components

If you are installing a very low-level JBoss Tools component such as `base`, the odds are very good that 
no matter what eclipse release you will be installing into will already contain all dependencies you need.  
If you're installing a locally-built top-level component such as `central` or `javaee`, you will need to install
many dependencies before being able to install your locally built unit. 

There are two primary ways to get all of these dependencies:

* Installing a recent JBoss Tools release or nightly build, or
* Installing our entire target platform, and also locally building and installing all dependencies that are part of JBoss Tools. 

If you are building a top-level element like `central`, though, and also have requirements on new API you have added
in another component such as `base` which has not yet made it into our nightly builds, you will need to install
such dependencies manually or from one of the public update sites. 

=== Installing a JBoss Tools release

Please see http://tools.jboss.org/downloads/installation.html

=== Manual dependency installation

To install the target platform portion, you'll want to see link:target_platforms/target_platforms_for_consumers.adoc#installing-a-target-platform-into-eclipse[Installing a target platform into Eclipse]. If you intend to often test local builds, you may find it beneficial to have a local folder with our entire target platform. 

Once this is done, you will need to discover all the dependencies of the component you are trying to install. You may find it easier to install a full release of JBoss Tools from a nightly or release update site, and then perform a second install of only those locally built features you changed yourself.  The each project's root pom will list which projects on which it depends. 

[NOTE]
====
For example, https://github.com/jbosstools/jbosstools-webservices/blob/master/pom.xml#L25-L36[Webservices] depends on https://github.com/jbosstools/jbosstools-server/blob/master/pom.xml[Server] and https://github.com/jbosstools/jbosstools-base/blob/master/pom.xml[Base]. The URLs that are resolved by default in these root poms can be computed by looking into the https://github.com/jbosstools/jbosstools-build/blob/master/parent/pom.xml#L75-L82[parent pom].
====

After this, you'll either need to install those dependencies from our JBoss Tools update site, or, build them locally and also install them.

=== Installing from a locally built update site

To install a component such as `jbosstools-base` or `jbosstools-server` into your eclipse installation:

* Select `Help -> Install New Software...` 
* Click `Add...`
* Optionally, provide a name 
* Browse to the location of your locally built update site, such as `file://${HOME}/jbt/jbosstools-server/site/target/repository/`
* Click `OK`
* If you have upstream dependencies, ensure you add those sites too. For example, Server depends on Base, and both depend on the target platform, so be sure to add these:
** If built locally, where `${HOME}` = `/home/username`:
*** `file://${HOME}/jbt/jbosstools-base/site/target/repository/`
*** `file://${HOME}/jbt/jbosstools-target-platforms/jbosstools/multiple/target/jbosstools-multiple.target.repo/`
** If not built locally:
*** http://download.jboss.org/jbosstools/builds/nightly/core/master/ (includes all of JBoss Tools and its http://download.jboss.org/jbosstools/targetplatforms/jbosstoolstarget/[target platform])
* If you're only installing from one component's update site:
** In the `Work with` field, choose the local site from which you want to install, and click `Select All`
* If you are installing from across multiple sites:
** Choose `--All Available Sites --`, then carefully select the feature you want to install
* Click `Next>`, accept the licences, and continue until you can press `Finish` to complete the install

If you experience errors, it is very likely you are missing some dependency. You may find it easier to install a full release of JBoss Tools from a nightly or release update site, and then perform a second install of only those locally built features you changed yourself.  The each project's root pom will list which projects on which it depends. 

[NOTE]
====
For example, https://github.com/jbosstools/jbosstools-webservices/blob/master/pom.xml#L25-L36[Webservices] depends on https://github.com/jbosstools/jbosstools-server/blob/master/pom.xml[Server] and https://github.com/jbosstools/jbosstools-base/blob/master/pom.xml[Base]. The URLs that are resolved by default in these root poms can be computed by looking into the https://github.com/jbosstools/jbosstools-build/blob/master/parent/pom.xml#L75-L82[parent pom]. 
====

== Everything's Installed, Now what? 

At this point you'll want to move forward to link:how_to_test_a_build.adoc[How to Test a Build]

