= Testing

== On existing RCP application

With Tycho 0.19.0, we could fix the long-standing issue https://issues.jboss.org/browse/JBIDE-13869[JBIDE-13869] (see https://github.com/jbosstools/jbosstools-build/commit/74b4acbeaeacaf4edd657bed6164da468fb39ca3[change in parent pom]). This will allow you to run your test with Maven against an RCP application which is available in your filesystem.
You can do it by simply running for example:

[sources,bash]
----
cd tests/my.test.bundle
mvn clean verify -Dtest.profileName=epp.package.jee -Dtest.installPath=/home/me/eclipse-4.4.2
----

If +test.installPath+ is not set, you get the default surefire behaviour which is to generate a simple minimal installation to run the tests in +target/work+.
More info about the profileName can be found in http://wiki.eclipse.org/Tycho/Testing_with_Surefire#p2Installed_on_provisioned_RCP_application . This works on any RCP application that relies on p2 (it's for example possible to run JBoss Tools inside Websphere Studio ;).

It's configured it so that by default, it is JBDS-friendly and set the jbds profileName. So to test on JBDS, you can omit the profile name and simply use:
[source,bash]
----
mvn clean verify -Dtest.installPath=/home/me/jbdevstudio-8.1.0.Beta1-SNAPSHOT/studio
----

Except a few exceptions, other surefire parameters, such as the very cool +debugPort+ parameter, can be used together with this mechanism. 

== Integration or other slow running tests

In general, code containing slow-running integration tests should be broken out and put in an `itests` folder. For details, see link:../source/how_to_add_a_test_plugin_or_feature.adoc#integration-or-other-slow-running-tests[How to add a new test plugin or feature to an existing JBoss Tools 4.x project].


== Remote Debugging

If you need to attach the Eclipse Debugger to your itests as they run in a console, you can do so with `-DdebugPort=8000`. For details, see link:../debugging/debug_tycho_tests.adoc[Debugging Surefire Tests].
