Testing
=======

On existing RCP application
---------------------------

With Tycho 0.19.0, we could fix the long-standing issue JBIDE-13869. This will allow you to run your test with Maven against an RCP application which is available in your filesystem.
You can do it by simply running for example:
  $ cd tests/my.test.bundle
  $ mvn clean verify -Dtest.profileName=epp.package.jee -Dtest.installPath=/home/me/eclipse-4.4.M2
If test.installPath is not set, you get the default surefire behaviour which is to generate a simple minimal installation to run the tests in target/work.
More info about the profileName can be found in http://wiki.eclipse.org/Tycho/Testing_with_Surefire#p2Installed_on_provisioned_RCP_application . This works on any RCP application that relies on p2 (in case you want to test JBoss Tools inside Websphere Studio ;).

We've configured it so that by default, it is JBDS-friendly and set the jbds profileName. So to test on JBDS, you can simply use:
  $ mvn clean verify -Dtest.installPath=/home/me/jbdevstudio-8.0.0.Alpha1-SNAPSHOT/studio

Except a few exceptions, other surefire parameters, such as the very cool debugPort parameter, can be used together with this mechanism. 
