= Process for updates to target platforms

Target platforms should not grow or change unexpectedly. 

Below is the process to follow for sanely changing the target platform to empower developers and keep churn to a minimum.

Goals:

. Avoid unnecessary churn (failed builds)
. Avoid adding unnecessary or incomplete dependencies
. Document why and when changes occur

Process:

. <<create-jira-outlining-the-request,Create JIRA outlining the request>>
. <<create-a-pull-request-with-your-changes,Create a pull request with your changes>>
.. <<fetch-sources,Fetch sources>> & <<build-target-platforms-locally,build locally>>
.. <<update-the-target-files,Update .target files>> & <<update-versions-of-ius-in-the-target-files,versions of IUs in .target files>>
.. <<update-versions-of-ius-in-the-target-files,Validate changes & test the new target platform>>
.. <<produce-a-p2diff-report,Produce a p2diff report>>
. <<send-mail-for-feedback,Send email>> to jbosstools-dev@lists.jboss.org requesting feedback. State expected feedback window (usually 1 week).
. <<await-feedback,Await feedback>> from build, affected team leads and project lead(s). For urgent changes, 1 project lead is OK.
. Apply the pull-request

== Create JIRA outlining the request

Use https://jira.jboss.org/jira/browse/JBIDE to open the issue.

*Type of bug*:

* _Feature Request_ if this change is introducing or removing a new feature/set of plugins

* _Bug_ if this is just to fix/update existing plugins

*Component*: _target-platform_ + releated components if applicable (i.e. _gwt_)

*Assignee*: (default)

*Fix version*: Set it to the corresponding JBoss Tools release

*Description*:

Template (copy into JIRA):

----
*Reason:* ...
*Project page/sources:* ...
*Version:* ....
*License and owner:* ...
*Original p2 repo:* http://third-party-vendor.com/path/to/updates-site/
*JBoss mirror:* http://downloads.jboss.org/jbosstools/updates/requirements/<projectName>
*Include Sources:* Yes|No
*Affected projects:*
*Include in JBDS:* Yes|No
*Type of dependency:* testing|central-only|distribution
*List of bundles added/removed:*
{code}
suggested diff on the .target files
{code}

If applicable:
*non-p2 repository:* ...
*non-p2 ids:* ...
----

Provide enough detail to explain why the change is needed, and what is required to verify. If you do not know the answer use "Unknown"; if not applicable, use "N/A".

* _Reason_: Why is the request needed, typical reasons are: "Required by new feature described in JBIDE-xyz", "Eclipse releasetrain update from Kepler M5 to M6" or "Removal because it conflicts with JBTIS and give bug describe at JBIDE-xyz"

* _License and owner_: Which license are these features available under and who are the maintainer? i.e. EPL, Google.

* _Original p2 repo_: which repository are the plugins/features from? eg., http://dl.google.com/eclipse/plugin/4.2

* _JBoss mirror_: mirror URL to use, eg. http://downloads.jboss.org/jbosstools/updates/requirements/tern/0.7.0.201412012159/

** If no mirror yet exists, look in https://github.com/nickboldt/jbosstools-download.jboss.org/tree/master/jbosstools/updates/requirements[updates/requirements/] for your requirement's folder. In that folder should be a build.xml file showing the URL and version to mirror. Please submit a pull request to update the URL or version, as applicable. 
** If no build.xml file exists for your requirement, please submit a pull request to create one.
** Once the PR is pushed, the build.xml script can then be run via https://jenkins.mw.lab.eng.bos.redhat.com/hudson/job/jbosstools-requirements/[this Jenkins job] (if you have VPN access).

* _Include Sources_: Are source bundles included in the mirror, or are sources available elsewhere? Use "included" or explain.

* _Affected projects_: Which projects are this known to affect, both inside and outside JBoss Tools core.

* _Include in JBDS_: Incubating (unstable) features should only be included in JBoss Tools.

* _Type of dependency_: is this just for testing (incl. in TP, but not in distribution), central-only (incl. in Central ONLY, not in the JBoss Tools or JBDS target platform), distribution (incl. in installer & update sites)

* _List of bundles added/removed_: https://github.com/irbull/p2diff[p2diff] report or pull-request preferred; if not available, please list features/plugins in alpha-sorted order

If your requirement is not available in an update site (p2 repository), eg. only available as maven artifact, please include more info:

* _non-p2 repository_: the exact repository URL (eg., Maven central or jboss repository) where the artifact exists

* _non-p2 ids_: list the exact ids, eg., for Maven state GAV (Group, Artifact, Version)

Non-p2 artifacts will be added to https://github.com/jbosstools/jbosstools-locus[JBoss Tools Locus] as p2 artifacts, so they can be included in the target platform.

== Create a pull request with your changes

=== Fetch sources

Following instructions cover the minimal edits needed for a review (a final Pull request needs updates to both jbosstools and devstudio target platform as needed)

 $ git clone git@github.com:jbosstools/jbosstools-target-platforms.git
 $ cd jbosstools-target-platforms
 $ git checkout <relevant version.x>

For Central:

 $ git clone git@github.com:jbosstools/jbosstools-discovery.git
 $ cd jbosstools-discovery
 $ git checkout <relevant version.x or master>

For the Integration Stack:

 $ git clone git@github.com:jbosstools/jbosstools-integration-stack.git
 $ cd jbosstools-integration-stack
 $ git checkout <relevant version.x or master>

=== Build target platform(s) locally

To build, you require specific versions of Java and Maven. Also, there is some Maven setup. 
The https://community.jboss.org/wiki/HowToBuildJBossToolsWithMaven3[How to Build JBoss Tools with Maven 3]
document will guide you through that setup.

This command will run the build, but will NOT download the contents of the target platform to disk:

    $ mvn clean verify

If you want to download the contents of the target platform to disk, do this:

    $ mvn clean verify -Pmultiple2repo

If you want to run the build and fetch source bundles at the same time as other bundles are being resolved, do this:

    $ mvn clean verify -Pmultiple2repo -Dmirror-target-to-repo.includeSources=true

[CAUTION]
====
Partial target platforms such as those for JBoss Central cannot be materialized with their sources included.
If you require sources, you must use a complete (merged) target platform which includes ALL upstream dependencies, but bear in mind this will produce a MUCH larger p2 repo, including all upstream dependencies and those dependencies' sources, too.
====

If you want to run the build and not fail if there's a problem w/ validation, do this:

    $ mvn clean verify -Pmultiple2repo -Dvalidate-target-platform.failOnError=false

If you just want to check if things compiles/builds you can run:

    $ mvn clean verify -Pmultiple2repo -DskipTest=true

But *do not* push changes without having the new and existing unit tests pass!

=== Update the *.target file(s)

Edit `jbosstools/multiple/jbosstools-multiple.target`. You may update an existing location or add a new one:

[source,xml]
----
    <location includeAllPlatforms="false" includeMode="slicer" type="InstallableUnit" includeSource="true">
      <repository location="http://download.jboss.org/jbosstools/updates/requirements/atlassian/3.2.2.v20130909/"/>
      <unit id="com.atlassian.connector.eclipse.jira.feature.group" version="3.2.2.v20130909"/>
      <unit id="com.thoughtworks.xstream" version="1.3.0.v20100826-1640"/>
      <unit id="org.joda.time" version="1.6.0.v20081202-0100"/>
    </location>
----

If your change affects JBDS too, edit `jbdevstudio/multiple/jbdevstudio-multiple-target` as well. 

For https://github.com/jbosstools/jbosstools-discovery/[JBoss Central], edit `jbtcentraltarget/multiple/jbtcentral-multiple.target` and/or `jbtearlyaccesstarget/multiple/jbtearlyaccess-multiple.target`.

For the https://github.com/jbosstools/jbosstools-integration-stack/tree/master/target-platform[Integration Stack], edit the applicable .target files in `target-platform/`.

[NOTE]
If you do not have a mirrored download.jboss.org location use the vendor's URL, so that the .target file can be easily tested.

Now build and validate the changed target platform. 


=== Update versions of IUs in the .target files

When moving from one version of the target to another, the steps are:

. If this is a new target platform (rather than changes to an existing SNAPSHOT) increment the target platform versions contained in all the pom.xml and *.target files.

. Manually update the URLs contained in the *.target files (as noted above).

. Validate the target platform. https://github.com/jbosstools/jbosstools-build-ci/tree/master/util/verifyTarget.sh[You can use a script to automate these next 4 steps].
+
[CAUTION]
====
. Regenerate the IU versions, using https://github.com/jbosstools/jbosstools-maven-plugins/wiki[org.jboss.tools.tycho-plugins:target-platform-utils], and validate the results.
* `mvn -U org.jboss.tools.tycho-plugins:target-platform-utils:0.19.0-SNAPSHOT:fix-versions -DtargetFile=/path/to/some.target`

. Resolve & verify the new target platform, optionally including sources (which will produce a MUCH larger on-disk footprint).
* `mvn (clean) install -Pmultiple2repo`
or
* `mvn (clean) install -Pmultiple2repo -Dmirror-target-to-repo.includeSources=true`

. https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/installFromTarget.sh[Install the new target platform] into a clean Eclipse JEE bundle to verify that everything can be installed, using http://download.jboss.org/jbosstools/updates/scripted-installation/director.xml[a headless p2.director script]. http://download.jboss.org/jbosstools/updates/scripted-installation/[More info].

. Produce a https://github.com/irbull/p2diff[p2diff] report.
====

. If applicable, test your locally built target platform in another build.

* `mvn verify -Dtpc.targetKind=multiple -Dtpc.version=<version-you-built>`
.. Note that `tpc.version` is the version listed in the `pom.xml` file of the target platform ( eg., `4.40.0.Beta4-SNAPSHOT`) and `tpc.targetKind` is set to `multiple` since the default (`unified`) will not work before the target platform (.target and site) are published to Nexus and http://download.jboss.org/jbosstools/targetplatforms/[download.jboss.org]
.. If everything builds OK, can be installed (see install validation step in <<updating-versions-of-ius-in-target-files,Update versions of IUs in the .target files>>), and you can use the new functionallity needed by the change, commit your change to a topic branch and submit a pull request for your update.

. Follow the https://github.com/jbosstools/jbosstools-devdoc/blob/master/building/target_platforms/target_platforms_updates.adoc[release guidelines] for how to commit to a topic branch, and announce target platform changes.

. Check in updated target files &amp; push to the branch.


==== Produce a p2diff report

As noted above, you can create a https://github.com/irbull/p2diff[p2diff] report to clarify what IUs will change if your PR is applied. For example:

[source,bash]
----
git clone https://github.com/irbull/p2diff.git
pushd p2diff/org.eclipse.equinox.p2.example.p2diff.releng/ && mvn install && popd
pushd p2diff/org.eclipse.equinox.p2.example.p2diff.packaging/target/products/org.eclipse.equinox.p2.example.p2diff.product
cd linux/gtk/x86_64 # or your preferred platform
./p2diff \
 file://${HOME}/tru/jbosstools-target-platforms/jbosstools/multiple/target_with_com.google/jbosstools-multiple.target.repo/ \
 file://${HOME}/tru/jbosstools-target-platforms/jbosstools/multiple/target/jbosstools-multiple.target.repo/
popd

< com.google.gwt.eclipse.sdkbundle.feature.feature.group [2.5.1] 
< com.google.gwt.eclipse.core [3.4.2.v201310081834-rel-r43] 
< com.google.gdt.eclipse.core [3.4.2.v201310081834-rel-r43] 
< com.google.gdt.eclipse.platform [3.4.2.v201310081834-rel-r43] 
< com.google.gwt.eclipse.sdkbundle.feature.feature.jar [2.5.1] 
< com.google.gwt.eclipse.oophm [3.4.2.v201310081834-rel-r43] 
< com.google.gwt.eclipse.sdkbundle [2.5.1] 
=== Summary ===
file:///${HOME}/tru/jbosstools-target-platforms/jbosstools/multiple/target_with_com.google/jbosstools-multiple.target.repo/ contains 7 unique IUs

----


== Request feedback and review

=== From the whole team

In most cases, the change can impact multiple components so the whole team should be notified about the change request
to verify the suggested change doesn't break them.

Send feedback request email to jbosstools-dev@lists.jboss.org, listing the PR, JIRA link(s), steps to use, and additional info if desired.

Past examples:

* http://lists.jboss.org/pipermail/jbosstools-dev/2014-April/008765.html[For 4.40.0.Beta2: Remove GPE/GWT, fix Atlassian]
* http://lists.jboss.org/pipermail/jbosstools-dev/2014-March/008683.html[For 4.40.0.Beta1: Add Sapphire] 

[info]
Using the template below will get you started, but you will still need to fill in these details:

* PR # and JIRA(s)
* https://github.com/irbull/p2diff[p2diff] report

Template:
[source,bash]
----

# configure these to generate the email body
TARGET_PLATFORM_VERSION=4.40.0.Beta2-SNAPSHOT
TOPIC_BRANCH=JBIDE-12345 # use 4.40.x or similar branch if PR is already applied
GITHUB_USER=mickaelistra # or nickboldt, etc. Use "origin" if PR is already applied
DEADLINE="7 days" # or "2 days" or "24 hours"

echo "
Subject:

Proposed change to JBT ${TARGET_PLATFORM_VERSION} target platform:

Body:

Here is a proposal for a change to the JBoss Tools ${TARGET_PLATFORM_VERSION} target platform: 

https://github.com/jbosstools/jbosstools-target-platforms/pull/FIXME_PR_NUMBER

It consists in the following changes:

* JBIDE-FIXME: Description of change
* JBIDE-FIXME_TOO: Description of other change


p2diff reports are attached to the related JIRA(s).

Please review the above PR(s), as it will be applied ASAP.
You can use the following to build & test the target-platform locally against your component(s).

Build target-platform:
  $ cd jbosstools-target-platforms
  $ git fetch origin pull/FIXME_PR_NUMBER/head
  $ git checkout FETCH_HEAD
  $ cd jbosstools/multiple
  $ mvn clean install

Try with just built target-platform:
  $ cd /path/to/your/component
  $ mvn clean verify -Dtpc.version=${TARGET_PLATFORM_VERSION} -Pmultiple.target
--

If you want to perform a scripted install of the entire target platform 
into your local Eclipse or JBDS instance, you can now do so with this 
script:

https://github.com/jbosstools/jbosstools-build-ci/blob/master/util/installFromTarget.sh

Usage is documented in the above script, and in this README:

https://github.com/jbosstools/jbosstools-target-platforms/tree/master#updating-versions-of-ius-in-target-files

--

More info:

  (if applicable)
"

----

Then *Await feedback*: Generally, developers should have 7 days to review a proposed change. However, for more urgent
changes (such as to fix a broken contribution from a previous PR or to remove something on which no projects still depend),
*1 or 2 days* may be sufficient. For components that are known to be potentially affected, directly ping their developers
via the mailing-list or IRC to make sure they try it.

Be sure to state the deadline in the email so devs & project leads know the urgency.

=== or, from requester only

When the following conditions are met:

. Only one component is affected
. The requester is the lead of the only affected component
. There is no IU added/removed
. It's only an update of a project known to be snapshot

Then, we can assume that the requester's feedback is enough, and ask for review directly on the Jira. If requesters gives a +1
for a given PR.

== Notify the team

When the change is applied and that TP has been rebuilt and made available, send a mail to jbosstools-dev to notify about that change.
