= Proposal for updates to targetplatforms

We need to be careful about our targetplatform not growing or change
too uncontrollable. Below is a suggestion for a process that attempts
to find middleground between being able to add anything by developers
for testing and exploration but once it goes into the master repo it
should have gone through a sanity check that goes beyond just "can it
compile".

Goals for the process is to:

. Avoid unnecessary churn in failed builds because of target platform changes
. Avoid adding dependencies to the target platform that are bad or unnecessary
. Be able to trace why and when changes were made to the target platform

Suggestion:

. <<create-jira-outlining-the-request,Create jira>>
. <<create-pull-request-and-test,Create Pull-request with changes, test it locally add link to jira>>
. Send email to jbosstools-dev@lists.jboss.org requesting feedback
. Await approvals from build, affected team leads and project lead(s).
  In case of urgency build + one project lead is considered ok, but should be the exception.
. Apply the pull-request

== Create Jira outlining the request

Use https://jira.jboss.org/jira/browse/JBIDE to open the issue.

*Type of bug*:

_Feature-Request_ if this change is introducing or removing a new feature/set of plugins

_Bug_ if this is just to fix/update existing plugins

*Component*: _target-platform_ + releated components if applicable (i.e. _gwt_, and none if global used dependency)

*Assignee*: Leave it to its default setting

*Fix version*: Set it to the corresponding JBoss Tools release or set of releases this is needed/intended for.

*Description*:

Template:

  Reason:
  License and owner:
  Original repository: http://
  JBoss Mirrored repository: http://downloads.jboss.org/jbosstools/updates/requirements/propername
  Source:
  Affected projects:
  Required in devstudio: Yes|No
  Type of dependency: testing|central-only|distribution
  List of bundles added/removed:

Provide enough detail for those checking the issue and those wanting to try out the suggested changes have enough info to do so
without navigating too many jiras/repos etc. If you do not know the answer to these put "Unknown" as answer and if not applicable put "N/A"

_Reason_: Why is the request needed, typical reasons are: "Required by new feature described in JBIDE-xyz", "Eclipse releasetrain update from Kepler M5 to M6" or "Removal because it conflicts with JBTIS and give bug describe at JBIDE-xyz"

_License and owner_: Which license are these features available under and who are the maintainer ? i.e. EPL, Google.

_Owner and Original repository_: which repository are the plugins/features from ? i.e. http://dl.google.com/eclipse/plugin/4.2

_JBoss Mirrored repository_: Which repository on http://downloads.jboss.org/jbosstools/updates/requirements/ are the original repostiory mirrored to or should be mirrored to, i.e. http://downloads.jboss.org/jbosstools/updates/requirements/gwt/3.1.0.v201208080121-rel-r42/

_Source bundle availability_: Does the repository include source bundles for these or are the source code available elsewhere ?

_Affected projects_: Which projects are this known to effect ? Inside and outside of JBoss Tools core.

_Required in devstudio_: If the plugin is only needed in JBoss Tools for an incubation like feature it should not be in devstudio target platform.

_Type of dependency_: is this just for testing (incl. in TP, but not in distribution), central-only (incl. on central but not to be used by our components directly), distribution (incl. in installer/associated updatesite)

_List of bundles added/removed_: Can be a link to a pull-request or pasted diff for .target; if not available list the plugins in sorted order so easier to browse/compare.

=== Requirements that are not available in a p2 repository

In case your requirement is not available in a p2 repository (i.e. only available as maven artifacts since it is not a p2 nor osgi artifact) we'll need at bit more details
added.

_non-p2 repository_: which repository are they located in (i.e. Maven central or jboss repository - please include the exact url you want them from)
_non-p2 id's_: what are the id's from this repository, in case of Maven it is the GAV (Group, Artefact, Version)

   non-p2 repository:
   non-p2 id's:

At the moment of writing we don't have an "orbit" to put these in - awaiting the first TP request to work out those details.

== Create Pull request and test

Following instructions cover the minimal edits needed for a review (a final Pull request needs updates to both jbosstools and devstudio target platform as needed)

 $ git clone git@github.com:jbosstools/jbosstools-target-platforms.git
 $ cd jbosstools-target-platforms
 $ git checkout <relevant version.x>
 $ cd jbosstools/multiple

Edit `jbosstools-multiple-target`, update an existing location or add as necessary, for example:

[source,xml]
----
 <location includeAllPlatforms="false" includeMode="planner" includeSource="true" type="InstallableUnit">
      <unit id="com.android.ide.eclipse.ddms.feature.group" version="21.1.0.v201302060044-569685"/>
      <unit id="com.android.ide.eclipse.adt.feature.group" version="21.1.0.v201302060044-569685"/>
      <repository location="https://dl-ssl.google.com/android/eclipse"/>
    </location>
----

Note:
If you do not have a mirrored download.jboss.org location use the direct url - importance is to get a .target file that can be easily tested.


Now build the target platform:

 $ mvn install

If this is the first time you build the target platform it will take a while (can be hours dependening on your network connection),
but if have built or used the target platform before you should be done within in minutes.

Once this is built you can test it in your component build by running:

 $ mvn verify -Dtpc.targetKind=multiple -Dtpc.version=4.30.5.Alpha3-SNAPSHOT

where the `tpc.version` is the version listed in the `pom.xml` file of the target platform and 'tpc.targetKind' is set to 'multiple' since the default ('unified') will not work when the target platform is not yet built and published publically.

If everything is building and it is possible to use the functionallity needed by the fix go ahead and open a pull request.

== Send mail for feedback

Send email to jbosstools-dev@lists.jboss.org requesting feedback.

Have the mail list PR and Jira and link/text on how to try it out. See the following template.
----
Hi all,

Here is a proposal for a new 4.31.0.Alpha1-SNAPSHOT target platform: https://github.com/jbosstools/jbosstools-target-platforms/pull/19
It consists in the following changes:
* JBIDE-15382 (Move to Kepler SR1 RC1/RC2)
** some projects are still using same version that we had for Kepler release (Birt, jetty, SWTBot)
** most projects have contributed a RC1 build
** some projects (Orbit, EGit) already contributed a RC2 build

Please review this PR and yell if there is anything shocking. You can use the following stuff to try to build build the TP locally and try out against your component:
  
Build target-platform:

  $ cd jbosstools-target-platforms
  $ git fetch mistria JBIDE-15382
  $ git checkout FETCH_HEAD
  $ cd jbosstools/multiple
  $ mvn clean install -P \!multiple2repo
  
Try with just built target-platform:
  $ cd /path/to/your/component
  $ mvn clean verify -Dtpc.version=4.31.0.Alpha1-SNAPSHOT -Pmultiple

Cheers,
----

== Await feedback

TBD: how/when/criteria to put into master.


