= Build cascade & results

Each year our process for building JBoss Tools & Red Hat Developer Studio evolves and improves,
so each year our process documentation is by necessity also evolving (and hopefully improving, too).

The basic workflow can be defined as follows:

1. For the JBoss Tools component projects:

* publish a /mars/snapshots/builds/JOB_NAME/BUILD_NUMBER/ for each build, with automated cleanup,
* publish a composite site in /mars/snapshots/builds/JOB_NAME/ pointing into all the BUILD_NUMBER/all/repo/ folders,
* publish a /mars/snapshots/builds/JOB_NAME/latest/ symlink to the latest job
* produce buildinfo.json inside the /all/repo/ folder

2. For JBoss Tools, we first create a composite site of the above sites, as this is so far the best way to provide a "gatekeeper" build to decide when to rebuild/republish the aggregate sites. Here's where those composite sites exist:

* http://download.jboss.org/jbosstools/mars/snapshots/builds/_composite_/core/master/compositeArtifacts.xml

3. Then, for JBoss Tools, we build a series of aggregate update sites (core, coretests, central, earlyaccess).

4. For Red Hat Developer Studio, we then we build the JBoss Developer Studio update site, and use that to build the installers.

All builds depend on their respective target platforms being built and up-to-date with the latest upstream dependencies from Eclipse and other third-party vendors.

 * http://download.jboss.org/jbosstools/targetplatforms/
 * https://devstudio.redhat.com/targetplatforms/

For the latest list of projects & links to their builds, logs & output, see:

https://github.com/jbosstools/jbosstools-devdoc/blob/master/list_of_projects.adoc

For the relationships between component projects (deprecated), see:

http://download.jboss.org/jbosstools/builds/cascade/swimlanes.html[http://download.jboss.org/jbosstools/builds/cascade/swimlanes.html]



