= Using the PDE Source Lookup plugin

This document explains how to install, then use the PDE Source Lookup plugin to automatically fetch missing source bundles from enabled p2 repositories, when opening a bundle jar (similar to m2e).

It's also possible to fetch all sources from the `Plug-in Dependencies` classpath container. Simply right-click and select `Download Bundle Sources`.

Sources are cached to `~/.eclipse/org.jboss.tools.pde.sourcelookup.core/sources`. That folder can be changed in `Preferences` > `Plug-in Development` > `Source Lookup`.

[NOTE]
====
Because the `Plug-in Dependencies` classpath container doesn't keep new attached sources on workspace restart (link:https://bugs.eclipse.org/bugs/show_bug.cgi?id=492204[EBZ 492204]), the PDE Source Lookup plugin automatically reattaches thoses sources upon restart.
This behavior can be disabled in `Preferences` > `Plug-in Development` > `Source Lookup`.
====

== Installation
* Requires an Neon or Oxygen installation, and Java 8.
* In Eclipse, either:
** go to `Help` > `Eclipse Marketplace…` to search PDE Source Lookup from the link:https://marketplace.eclipse.org/content/pde-source-lookup[Eclipse Marketplace]
** go to `Help` > `Install New Software...` and add one of these p2 repositories:
*** Stable: https://dl.bintray.com/fbricon/poc/pde.source.lookup/0.0.4.201612181944
*** CI: http://download.jboss.org/jbosstools/builds/staging/pde.source.lookup/all/repo/

== Contributing

Want to contribute? See the link:https://github.com/fbricon/pde.source.lookup[pde.source.lookup] project at Github.
