= Third Party Library Dependencies

Adding third party libraries to be bundled in your plugin is something that should be done rarely and only by seeking feedback on the mailto:jbosstools-dev@lists.jboss.org[jbosstools-dev@list.jboss.org] mailing list. 

== Do not push libraries into github

Adding third-party libraries to your github repository makes your repository very large and slow to download. This is not a generally approved method of adding dependencies to your plugin. In extreme circumstances it may be approved on a case-by-case basis, and only after discussion on the mailto:jbosstools-dev@lists.jboss.org[jbosstools-dev@list.jboss.org] mailing list. 

== So how do I add third party dependencies?

The proper way to bundle third-party libraries with your plugin is to add those dependencies to your pom.xml. This will ensure that those libraries are fetched during a build. The below example will fetch `jboss-logging-3.1.2.GA` and put it inside the `lib` folder inside your plugin. Add code similar to this example to your plugin's pom.xml:

```
      <properties>
          <jboss.logging.version>3.1.2.GA</jboss.logging.version>
        </properties>

        <build>
                <plugins>
                        <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-dependency-plugin</artifactId>
                                <version>2.7</version>
                                <executions>
                                  <execution>
                                    <id>get-logging</id>
                                    <goals>
                                      <goal>copy</goal>
                                    </goals>
                                    <phase>generate-resources</phase>
                                   </execution>
                                </executions>
                                <configuration>
                                      <artifactItems>
                                        <artifactItem>
                                          <groupId>org.jboss.logging</groupId>
                                          <artifactId>jboss-logging</artifactId>
                                          <version>${jboss.logging.version}</version>
                                        </artifactItem>
                                      </artifactItems>

                                      <skip>false</skip>
                                      <outputDirectory>${basedir}/lib/</outputDirectory>
                                </configuration>
                        </plugin>
```

== Add the dependencies to your `Manifest.mf` file

Open the `plugin.xml` editor and switch to the `Runtime` tab. On the bottom-right corner, you will see a section titled "Classpath". You should then add the dependency here. 

Alternatively, you can modify the `Manifest.mf` file directly as follows:

```
Bundle-ClassPath: .,
 lib/jboss-logging-3.1.2.GA.jar
```
