= Versioning rules

--

WARNING: This document may need to be updated or grammar-checked.

--

[cols="a", options="header"]
|===
|
DRAFT: This is a draft of how versioning are used in jboss tools
projects - currently based on current "defacto" and orally agreed on
versioning used in the related project(s)
|===

JBoss projects in general follows the general naming at
https://community.jboss.org/wiki/JBossProjectVersioning.

Plugins/features and even other components should be versioned according
to http://wiki.eclipse.org/Version_Numbering

The rest of this document tries to cover what is not specified in these
two documents and if there are exceptions to it.

Component - generic term used for something that is versioned. Could be
a plugin, feature, target platform, product, project, update site, etc.

Module - A set of components, for example:
https://github.com/jbosstools/jbosstools-hibernate/ or https://github.com/jbosstools/jbosstools-base

== Naming clarifications

Both JBoss and OSGi versioning rules say there are four parts to the
versioning scheme.

JBoss refers to these as: major.minor.micro.qualifier

Eclipse & OSGi use: major.minor.service.qualifier

We consider these to be equal, i.e. micro == service.

=== Always use numerical option

JBoss rules state the numeric option on qualifiers are optional, i.e.
Alpha is ok without a number. We always add the number for consistency
and that we know we are more than likely to have multiple of them.

The only qualifier that cannot have a numeric is Final. Final is final.

== Expected versioning sequence during development

When you do development you choose the right x.y.z for the next
upcoming/planned release, i.e. 2.3.0.

A 2.3.0 that is all new and going to be used by other in-development
components starts out by being named 2.3.0.Alpha1 and then progress
through bumping the qualifier until you reach 2.3.0.Final.

Example:

[cols="",]
|============
|2.3.0.Alpha1
|2.3.0.Alpha2
|2.3.0.Beta1
|2.3.0.CR1
|2.3.0.Final
|============

The exact number of alphas/betas/cr's might be planned for but reality
might kicks in and add/subtract some during development; what is
important that the qualifier keeps incrementing lexicographically to
have a deterministic ordering for both humans and machines.

== When does a component go from Alpha to Beta to CR ?

The general rules (taken from JBoss description but with a clearer
layout):

* Alpha - "for early releases that are not API complete, but have
usuable new functional capabilities where the community can benefit from
those new capabilites, plus contribute to the testing and fixing of
those new capabilities."
* Beta - "for releases where the release is API complete, but its not
completely tested, or there may even be questions about the API itself,
that may change, even though the implementation is complete."
* CR (Candidate Release) - "for releases that we anticipate can be the
GA (ed. Final) release, but we need the community to help validate the
release."

Another important part is that your component should not be marked of
higher quality than any of its dependencies. i.e. if you are using a
dependency that is in Alpha you cannot be in CR1 since the subcomponent
can/will change.

== When does a component go Final ?

The simple rule is that a component goes Final once itself and all its
subcomponent are Final.

This rule should be uphold and any deviance from it considered bad and
fixed. If it happens be clearly agreed and documented on which subpart
has issues.

== When does a component start increasing its micro ?

Once the release have gone final, i.e. 2.3.0.Final the qualifiers cannot
"move" more for that micro release. After this the component dependent
on its development pase and phase do either a full development cycle:

[cols="<",]
|============
|2.3.1.Alpha1
|2.3.1.Alpha2
|etc.
|============

If the changes are pure and simple bugfixes and you got plenty of tests
to verify this you can directly do

[cols="",]
|===========
|2.3.1.Final
|===========

== What if I run out of numeric numbers, i.e. Alpha9 > Alpha10

If this ever occurs it most likely is because of too many broken
releases and maybe using a SNAPSHOT mechanism would be better for your
component.

In this case the option is to use "respin-qualifiers" to "extend" the
numbers range, i.e. Alpha9a, Alpha9b etc.

== What if Final is released and there is a bug found ?

Example: you just released 2.3.0.Final and minutes/hours after a serious
bug is found in your component or a subcomponent. What to do ?

Fix the bug/upgrade to the subcomponent that does not have the bug and
version accordingly which hopefully would be just 2.3.1.Final.

In the worst case that the subcomponent needs to be upgraded to
something that breaks/adds API you would need to do a 2.4.0 instead -
but in that case you cannot just do a 2.4.0.Final directly. This would
require a new development phase - thus should be avoided at all costs by
getting the subcomponent fixed without breaking API.

== Bumping of versions across major versioned development streams

This concerns how we handle versioning conflicts between streams.

Let's say if you have a component versioned 2.4.0 just released as part
of JBoss Tools 4.2/Developer Studio 8.0 and a new major development
starts for JBoss Tools 4.3/Developer Studio 9.0 - what do you do with
the component versioned at 2.4.0 ?

The current default is to bump the minor version to 2.5.0.

The question often asked is why not just rely on bump to 2.4.1 or
2.4.100 as done in some Eclipse.org projects ?

The main reasons for this is:

* if bumping to 2.4.1 in the new branch, the old branch can no longer do
maintanence updates (bad)
* if bumping to 2.5.100 that is solved and is definitely a good model to
strive for, but since we are in a new development stream moving from
i.e. Kepler to Luna you are changing the build and test dependencies and
are you then confident enough to say your component still works on
Kepler ? (it should since you haven't bumped the major version)

Thus historically we've bumped the minor version between development
streams since then there are no false promises about backwards
compatability.

== Why do I need to bump my module in a bundle that has no code changes
when another bundle in the bundle changes for a maintanence release ?

This situation occurs when you have multiple components in one module
(repository).

For example `base` has both `foundation` and `common` and they were
released as foundation-1.2.0.Final and common-2.4.0.Final. For a
maintanence release `foundation` has a bugfix made and according to the
basic OSGI/JBoss versioning rules above it bumps to at least
foundation-1.2.1.Final. Now what should common do ?

Most would say `common` should not need to bump its version since it has
not changed, but unfortunately that assumes that `common` is not being
rebuilt either.

In the current setup of JBoss Tools builds the whole repository is
rebuilt and published as one updatesite, which means `common` _will_ be
rebuilt and thus will as a minimum get a new timestamp in the qualifier
(i.e. 2.4.0.Final-v20140912-2255-B61 and 2.4.0.Final-v20141011-2258-B67)
and that again breaks the basic versioning rules of artifacts.

Thus if you do not bump `common` it will A) have done different binary
releases of the same version B) still result in updates to the user
__anyway__.

Thus the policy is that if a module gets rereleased all
bundles/components withint it needs to _at least_ bump the micro version
no matter if they had changes or not.
